# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 561, 281))
        self.backgroundLabel.setObjectName("backgroundLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        self.gameMenu = QtWidgets.QMenu(self.menubar)
        self.gameMenu.setObjectName("gameMenu")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.quitBtn = QtWidgets.QAction(MainWindow)
        self.quitBtn.setObjectName("quitBtn")
        self.newGameAction = QtWidgets.QAction(MainWindow)
        self.newGameAction.setObjectName("newGameAction")
        self.gameMenu.addAction(self.newGameAction)
        self.menubar.addAction(self.gameMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backgroundLabel.setText(_translate("MainWindow", "ы"))
        self.gameMenu.setTitle(_translate("MainWindow", "Игра"))
        self.action.setText(_translate("MainWindow", "Новая игра"))
        self.quitBtn.setText(_translate("MainWindow", "выход"))
        self.newGameAction.setText(_translate("MainWindow", "новая игра"))
